# Generated by Django 5.1.3 on 2024-11-17 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalAttainment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('house', models.ImageField(blank=True, null=True, upload_to='houses/')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lvl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.educationalattainment')),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.barangay')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('brgy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_brgy', to='management.barangay')),
                ('civil_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.civilstatus')),
                ('educational_attainment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.educationalattainment')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.gender')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.individualhouse')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.occupation')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.religion')),
                ('schools', models.ManyToManyField(blank=True, to='management.schoolname')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.sitio')),
            ],
        ),
    ]
