# Generated by Django 5.1.3 on 2024-11-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='individualImages/'),
        ),
        migrations.AddField(
            model_name='individual',
            name='precinct_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='civil_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.civilstatus'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='educational_attainment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.educationalattainment'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.individualhouse'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.occupation'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.religion'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.sitio'),
        ),
    ]
